### ISSUE TITLE
Support of tuples

### ISSUE THREAD

**Issue by profiprog** [cyclosproject/ng-swagger-gen#131]
JSON schema definition allows to define type for each array item like this:
```yaml
...
definitions:
  Records:
    type: array
    items:
      - type: string
      - type: number
    minItems: 2
    maxItems: 2
```
It generates model like:
```ts
/* tslint:disable */

export type Records = Array<any>;
```
Expected model is:
```ts
/* tslint:disable */

export type Records = [string, number];
```
