### ISSUE TITLE
Enum does not work on number type

### ISSUE THREAD

**Issue by profiprog** [cyclosproject/ng-swagger-gen#133]
Enum constants are currently supported only for string type. Support for numeric types (number, integer) doesn't works.
If I have model like:
```yaml
...
definitions:
  Test:
    type: object
    properties:
      cardinals:
        type: string
        enum:
          - north
          - east
          - south
          - west
      orientation:
        type: integer
        enum:
          - 0
          - 90
          - 180
          - 270
```
Generates model like:
```ts
/* tslint:disable */
export interface Test {
  cardinals?: 'north' | 'east' | 'south' | 'west';
  orientation?: number; // <-- this allows to set any number
}
```
But expected model is like:
```ts
/* tslint:disable */
export interface Test {
  cardinals?: 'north' | 'east' | 'south' | 'west';
  orientation?: 0 | 90 | 180 | 270;
}
```
