### ISSUE TITLE
Add support for const (as special case of enum constant)

### ISSUE THREAD

**Issue by profiprog** [cyclosproject/ng-swagger-gen#134]
JSON schema property [const](https://ajv.js.org/keywords.html#const) is more readable form of a one-element enum.
A simple examle:
```yaml
...
definitions:
  Test:
    type: object
    properties:
      type:
        type: string
        const: INTERNAL
```
generates model like:
```ts
/* tslint:disable */
export interface Test {
  type?: string; // <-- allows to set any string here
}
```
but expected model is:
```ts
/* tslint:disable */
export interface Test {
  type?: 'INTERNAL';
}
```

This is useful if I like to define certain set of properties depending on property type. Like for example:
```yaml
definitions:
  Request:
    type: object
    required:
      - input
    properties:
      input:
        anyOf:
          - type: object
            required:
              - type
              - latitude
              - longitude
            additionalProperties: false
            properties:
              type:
                type: string
                const: 'ADDRESS'
              latitude:
                type: number
                format: double
              longitude:
                type: number
                format: double
          - type: object
            required:
              - type
              - address
            additionalProperties: false
            properties:
              type:
                type: string
                const: 'GEOLOCATION'
              address:
                type: string
```
generates model like:
```ts
/* tslint:disable */
export interface Request {
  input: {type: 'ADDRESS', latitude: number, longitude: number} |
         {type: 'GEOLOCATION', address: string};
}
```
