### ISSUE TITLE
Add support for anyOf/oneOf at top level of object definition

### ISSUE THREAD

**Issue by profiprog** [cyclosproject/ng-swagger-gen#135]
Currently anyOf/oneOf is supported only in properties. But at top level object is not. For example
```yaml
...
definitions:
   Request:
    anyOf:
      - type: object
        required:
          - latitude
          - longitude
        additionalProperties: false
        properties:
          latitude:
            type: number
            format: double
          longitude:
            type: number
            format: double
      - type: object
        required:
          - address
        additionalProperties: false
        properties:
          address:
            type: string
```
generates model like:
```ts
/* tslint:disable */
export interface Request {
}
```
but expected mode is something like this:
```ts
/* tslint:disable */
export type Request = {latitude: number, longitude: number} | {address: string};
```
