### ISSUE TITLE
All properties in nested objects are required, even if they are not defined so

### ISSUE THREAD

**Issue by profiprog** [cyclosproject/ng-swagger-gen#136]
For example
```yaml
...
definitions:
  WriteRequest:
    type: object
    required:
      - entry
    additionalProperties: false
    properties:
      entry:
        type: object
        required:
          - id
          - name
        additionalProperties: false
        properties:
          id:
            type: string
            format: uuid
          name:
            type: string
          age:
            type: integer
```
generates model like:
```ts
/* tslint:disable */
export interface WriteRequest {
  entry: {id: string, name: string, age: number}; // <-- age should be optional
}
```
but expected model is
```ts
/* tslint:disable */
export interface WriteRequest {
  entry: {id: string, name: string, age?: number};
}
```
