### ISSUE TITLE
If additionalProperties are not defined they should be allowed

### ISSUE THREAD

**Issue by profiprog** [cyclosproject/ng-swagger-gen#137]
For examle:
```yaml
definitions:
  WriteRequest:
    type: object
    required:
      - records
    additionalProperties: false
    properties:
      records:
        type: array
        items:
          type: object
          required:
            - id
          properties:
            id:
              type: string
              format: uuid
```
generates model like:
```ts
/* tslint:disable */
export interface WriteRequest {
  records: Array<{id: string}>; // <-- record does not allow additional fields
}
```
but expected is:
```ts
/* tslint:disable */
export interface WriteRequest {
  records: Array<{id: string, [key: string]: any}>;
}
```
