### ISSUE TITLE
Support for Multiple Types

### ISSUE THREAD

**Issue by profiprog** [cyclosproject/ng-swagger-gen#149]
[Multiple types](https://cswr.github.io/JsonSchema/spec/multiple_types/) allows shorter definition of complex types. For example definition:
```yaml
...
definitions:
  Request:
    type:
      - integer
      - string
    minimum: 2
    minLength: 4
```
currentrly generates code:
```typescript
/* tslint:disable */
export type Request = any;
```
but it should be like:
```typescript
/* tslint:disable */
export type Request = number | string;
```
