### ISSUE TITLE
Fix for type null

### ISSUE THREAD

**Issue by profiprog** [cyclosproject/ng-swagger-gen#150]
Sometime I need define type of property to be `null`. For example
```yaml
  ...
  Request:
    required:
      - query
    properties:
      query:
        anyOf:
          - type:
              string
          - type:
              'null'
```
currently generates code:
```typescript
/* tslint:disable */
export interface Request {
  query: string | any;
}
```
but expected is:
```typescript
/* tslint:disable */
export interface Request {
  query: string | null;
}
```
