### ISSUE TITLE
[ERROR] Body parameters not merged

### ISSUE THREAD

**Issue by victoressedi** [cyclosproject/ng-swagger-gen#183]
When you provide more than one body parameter the ng-swagger-gen does not merge them.

API Platform resource:
```

method: 'POST'
route_name: api_register_children
swagger_context:
           parameters:
                      -
                      in: body
                      name: branch
                      type: string
                      required: true
                      -
                      in: body
                      name: children
                      type: object
                      required: true
```

What it generates inside the method
```
let __body: any = null;
__body = params.children;
__body = params.branch;
```
